In [1]:
import numpy as np


# Data Types

In [10]:
np.int64   #Signed 64-bit integer types
np.float32 #Standard double-precision floating point
np.complex #Complex numbers represented by 128 floats
np.bool    #Boolean type storing TRUE and FALSE values
np.object  #Python object type
np.string_ #Fixed-length string type
np.unicode_ #Fixed-length unicode type

numpy.str_

# Creating Arrays¶


In [2]:
a = np.array([1,2,3])
print(a)
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
print(b)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)
print(c)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


# Initial Placeholders

In [3]:
np.zeros((3,4))  #Create an array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones((2,3,4),dtype=np.int16)   #Create an array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [5]:
d = np.arange(10,25,5)   # Create an array of evenly spaced values (step value) 

In [6]:
print(d)

[10 15 20]


In [7]:
np.linspace(0,2,9)    #Create an array of evenly spaced values

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [8]:
e = np.full((2,2),7)    # Create a constant array
print(e)

[[7 7]
 [7 7]]


# Inspecting Your Array

In [11]:
a.shape           #Array dimensions

(3,)

In [12]:
len(a)            #Length of array


3

In [13]:
b.ndim            #Number of array dimensions


2

In [14]:
e.size            #Number of array elements


4

In [15]:
b.dtype           #Data type of array elements


dtype('float64')

In [16]:
b.dtype.name      #Name of data type


'float64'

In [17]:
b.astype(int)     #Convert an array to a different type


array([[1, 2, 3],
       [4, 5, 6]])

# Arithmetic Operations

In [18]:
g = a - b    #Subtraction
print(g)

[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]


In [19]:
np.subtract(a,b)  #Subtraction


array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [20]:
b + a             #Addition


array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [21]:
np.add(b,a)    #Addition


array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [22]:
a / b          #Division


array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [23]:
np.divide(a,b) #Division


array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [24]:
a * b          #Multiplication


array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [25]:
np.multiply(a,b)   #Multiplication


array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [26]:
np.exp(b) #Exponentiation


array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [27]:
np.sqrt(b) #Square root

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [28]:
np.sin(a) #Print sines of an array


array([0.84147098, 0.90929743, 0.14112001])

In [29]:
np.cos(b) #Element-wise cosine


array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [30]:
np.log(a) #Element-wise natural logarithm


array([0.        , 0.69314718, 1.09861229])

# Comparison


In [34]:
a == b   #Element-wise comparison



array([[False,  True,  True],
       [False, False, False]])

In [35]:
a < 2    #Element-wise comparison


array([ True, False, False])

In [36]:
np.array_equal(a, b) #Array-wise comparison


False

# Aggregate Functions

In [37]:
a.sum() #Array-wise sum



6

In [38]:
a.min() #Array-wise minimum value


1

In [39]:
b.max(axis=0) #Maximum value of an array row


array([4., 5., 6.])

In [40]:
b.cumsum(axis=1) #Cumulative sum of the elements


array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [41]:
a.mean() #Mean


2.0

In [42]:
np.median(b) #Median



3.5

In [43]:
np.corrcoef(a) #Correlation coefficient


1.0

In [44]:
np.std(b) #Standard deviation


1.5920810978785667

# Copying Arrays 

In [46]:
h = a.view()   #Create a view of the array with the same data
np.copy(a) #Create a copy of the array
h = a.copy() #Create a deep copy of the array


In [47]:
h


array([1, 2, 3])

# Sorting Arrays

In [50]:
a.sort()  #Sort an array
c.sort(axis=0)  #Sort the elements of an array's axis
a

array([1, 2, 3])

# Slicing

In [52]:
a[0:2] #Select items at index 0 and 1

array([1, 2])

In [53]:
b[0:2,1] #Select items at rows 0 and 1 in column 1


array([2., 5.])

In [54]:
a[ : :-1] #Reversed array a array([3, 2, 1])


array([3, 2, 1])

In [55]:
c[1,...] #Same as [1,:,:]


array([[3., 2., 3.],
       [4., 5., 6.]])

In [56]:
b[:1] #Select all items at row 0 (equivalent to b[0:1, :])


array([[1.5, 2. , 3. ]])

# Transposing Array

In [57]:
i = np.transpose(b)          #Permute array dimensions


In [58]:
i.T                          #Permute array dimensions


array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

# Changing Array Shape

In [59]:
b.ravel()                    #Flatten the array


array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [60]:
g.reshape(3,-2)              #Reshape, but don’t change data


array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

# Adding/Removing Elements

In [62]:
np.append(h,g)               #Append items to an array


array([ 1. ,  2. ,  3. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [63]:
np.insert(a, 1, 5)           #Insert items in an array


array([1, 5, 2, 3])

In [64]:
np.delete(a,[1])             #Delete items from an array


array([1, 3])

# Combining Arrays

In [66]:
np.concatenate((a,d),axis=0) #Concatenate arrays


array([ 1,  2,  3, 10, 15, 20])

In [67]:
np.vstack((a,b))             #Stack arrays vertically (row-wise)


array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

# Splitting Arrays¶


In [70]:
np.hsplit(a,3)               #Split the array horizontally at the 3rd index


[array([1]), array([2]), array([3])]

In [71]:
np.vsplit(c,2)               #Split the array vertically at the 2nd index


[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 3.],
         [4., 5., 6.]]])]